version: 2
jobs:
  build:
    machine: true
    steps:
    - run:
        command: echo "fooがインストールされています"
workflows:
  main:
    jobs:
    - build
  version: 2

# Original config.yml file:
# version: 2.1
# jobs:
#   build:
#     parameters:
#       # \u771F\u507D\u5024\u306E\u30D1\u30E9\u30E1\u30FC\u30BF
#       preinstall-foo:
#         type: boolean
#         default: false
#     machine: true
#     steps:
#       - when:
#           condition: << parameters.preinstall-foo >>
#           steps:
#             - run: echo \"foo\u304C\u30A4\u30F3\u30B9\u30C8\u30FC\u30EB\u3055\u308C\u3066\u3044\u307E\u3059\"
#       - unless:
#           condition: << parameters.preinstall-foo >>
#           steps:
#             - run: echo \"foo\u304C\u30A4\u30F3\u30B9\u30C8\u30FC\u30EB\u3055\u308C\u3066\u3044\u307E\u305B\u3093\"
# 
# workflows:
#   main:
#     jobs:
#       - build:
#           # build\u30B8\u30E7\u30D6\u306B\u5BFE\u3057\u3066\u30D1\u30E9\u30E1\u30FC\u30BF\u3092\u6E21\u3059
#           preinstall-foo: true
