version: 2.1
commands:
  greeting:
    description: commandのサンプル
    parameters:
      # string（文字列）のパラメータ
      to:
        type: string
        default: ""
    steps:
      # << パラメータ >> でパラメータを使用する
      - run: echo Hello << parameters.to >>
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      # stepsでcommandを使う
      - greeting:
          # パラメータをcommandに渡す
          to: World
