version: 2.1
jobs:
  build:
    parameters:
      # 真偽値のパラメータ
      preinstall-foo:
        type: boolean
        default: false
    machine: true
    steps:
      - when:
          condition: << parameters.preinstall-foo >>
          steps:
            - run: echo "fooがインストールされています"
      - unless:
          condition: << parameters.preinstall-foo >>
          steps:
            - run: echo "fooがインストールされていません"

workflows:
  main:
    jobs:
      - build:
          # buildジョブに対してパラメータを渡す
          preinstall-foo: true
